export const FILAMENT_BRANDS = [
  "3D Fuel",
  "3DXTech",
  "Amazon Basics",
  "Amolen",
  "Atomic Filament",
  "Bambu Lab",
  "BASF",
  "BCN3D",
  "Colorfabb",
  "ColorFabb",
  "Das Filament",
  "Deezmaker",
  "E-Sun",
  "eSUN",
  "Elegoo",
  "Eryone",
  "Extrudr",
  "Fillamentum",
  "Filamentive",
  "Filamentum",
  "FormFutura",
  "Fusion Filaments",
  "Geetech",
  "Hatchbox",
  "Hello3D",
  "Inland",
  "iSANMATE",
  "Jayo",
  "Jessie",
  "Kexcelled",
  "Kingroon",
  "Kodak",
  "MakerBot",
  "MakerGeeks",
  "MatterHackers",
  "Mika3D",
  "Novamaker",
  "Orbi-Tech",
  "Overture",
  "Paramount 3D",
  "Plastic Jungle",
  "Polyalchemy",
  "Polymaker",
  "Printed Solid",
  "Prusament",
  "Push Plastic",
  "Raise3D",
  "Real Filament",
  "Rigid.ink",
  "Sainsmart",
  "Shaxon",
  "Solutech",
  "Spectrum",
  "Sunlu",
  "Tinmorry",
  "Tianse",
  "Verbatim",
  "Voxelpla",
  "Ziro",
  "Custom",
] as const;

export const FILAMENT_MATERIALS = [
  "PLA",
  "PLA+",
  "PETG",
  "ABS",
  "ASA",
  "TPU",
  "TPE",
  "PA (Nylon)",
  "PA-CF",
  "PAHT-CF",
  "PVA",
  "HIPS",
  "PC",
  "PC-CF",
  "PP",
  "PEEK",
  "PEI",
  "Wood Fill",
  "Metal Fill",
  "Marble",
  "Silk PLA",
  "Matte PLA",
  "High Speed PLA",
  "Other",
] as const;

export const NOZZLE_SIZES = [0.2, 0.4, 0.6, 0.8, 1.0] as const;

export const NOZZLE_MATERIALS = [
  "Brass",
  "Hardened Steel",
  "Stainless Steel",
  "Ruby",
  "Tungsten",
  "Copper",
  "Other",
] as const;

export const BUILD_PLATES = [
  "Textured PEI",
  "Smooth PEI",
  "Glass",
  "Spring Steel",
  "BuildTak",
  "Garolite",
  "Other",
] as const;

export const PRINTER_BRANDS = [
  "Bambu Lab",
  "Prusa",
  "Creality",
  "Anycubic",
  "Elegoo",
  "Flashforge",
  "Raise3D",
  "Ultimaker",
  "Formlabs",
  "Makerbot",
  "Voron",
  "Ratrig",
  "Other / Custom",
] as const;
